image: timbru31/node-chrome
# image: registry.gitlab.com/nikolayradoev/docker-images/chrome-mongo-node:20231

cache:
  key: "${CI_COMMIT_REF_SLUG}-client"
  paths:
      - client/node_modules/
  policy: pull

.only-client: &only-client
  only:
    refs:
      - master
      - merge_requests
    changes:
      - client/**/*
  cache:
    key: "${CI_COMMIT_REF_SLUG}-client"
    paths:
        - client/node_modules/
    policy: pull

stages:
  - install
  - lint
  - test
  # - deploy

install:client:
  stage: install
  <<: *only-client
  script:
    - cd client
    - npm install -g @angular/cli
    - npm ci --cache .npm --prefer-offline
  cache:
    key: "${CI_COMMIT_REF_SLUG}-client"
    paths:
        - client/node_modules/
        - client/.npm/
    policy: pull-push

lint:client:
  stage: lint
  needs: ["install:client"]
  allow_failure: true
  <<: *only-client
  script:
    - cd client
    - npm run lint

test:client:
  stage: test
  needs: ["install:client"]
  <<: *only-client
  script:
    - cd client
    - npm run coverage-gitlab
  dependencies:
        - install:client
  artifacts:
    paths:
      - client/coverage/

# deploy:client:
#   stage: deploy
#   <<: *only-client
#   script:
#     - docker-compose -f docker-compose.yml up -d
